### ISSUE TITLE
Cors error when trying to broadcast a transaction in localterra

### ISSUE THREAD

**Issue by movaldivia** [terra-money/terra.js#106]
I'm trying to create an UI for this tutorial: https://docs.terra.money/contracts/tutorial/implementation.html#start-with-a-template with React and using Docker to run localterra. I get the error when I try to broadcast.

My code: 

<img width="944" alt="Screen Shot 2021-07-18 at 21 48 34" src="https://user-images.githubusercontent.com/24725124/126091538-b6e47113-1de1-42f9-aee9-eb18794b43b0.png">

The error:

Messages: No 'Access-Control-Allow-Origin' header is present on the requested resource, cross-origin resource sharing error preflight missing allow origin header

<img width="1152" alt="Screen Shot 2021-07-18 at 21 50 07" src="https://user-images.githubusercontent.com/24725124/126091653-af974c7f-8136-4172-9998-93248692a0f0.png">

Any idea?

**Comment by movaldivia** [comment]
Found this issue https://github.com/terra-money/core/issues/409 don´t know if correlated

**Comment by movaldivia** [comment]
Needed to update my localterra with git pull!

**Comment by jimryan** [comment]
@movaldivia This was fixed in https://github.com/terra-money/core/pull/510, but I'm not sure if it's been released and if localterra is using it yet. It sounds like they are if it's working for you.

If not, or for anyone who comes across this and is looking for a different solution, you can compile `terracli` from `master` (which includes the above patch), and run your own LCD server with something like: `terracli rest-server --laddr=tcp://localhost:1316 --node=tcp://127.0.0.1:26657 --trust-node=true --unsafe-cors --home=/path/to/localterra --chain-id=localterra`

Then point your app to `localhost:1316` (I used a different port than localterra to avoid conflict with the included LCD server - an alternative approach would be to stop localterra's LCD server and run yours on 1317).
