### ISSUE TITLE
Unable to install @terra-money/terra.js

### ISSUE THREAD

**Issue by Abhishekkochar** [terra-money/terra.js#186]
Hi, I'm unable to install @terra-money/terra.js package. 
**Node version: v10.19.0**
I have tried the following command:
-sudo npm install @terra-money/terra.js
-npm install @terra-money/terra.js
-sudo npm install @terra-money/terra.js --unsafe-perm=true --allow-root
-sudo npm install -g @terra-money/terra.js @anchor-protocol/anchor.js --unsafe-perm=true --allow-root--> this one works but doesn't provide with @terra-money/terra.js  in package.json file

Error when running all these cmds, getting error:

npm ERR! code EACCES
npm ERR! syscall rename
npm ERR! path /mnt/c/pr0/test/node_modules/bufferutil
npm ERR! dest /mnt/c/pr0/test/node_modules/.bufferutil.DELETE
npm ERR! errno -13
npm ERR! Error: EACCES: permission denied, rename '/mnt/c/pr0/test/node_modules/bufferutil' -> '/mnt/c/pr0/arablevalidator/node_modules/.bufferutil.DELETE'

**Comment by RomainLanz** [comment]
Hey @Abhishekkochar! 👋🏻 

First of all, you are running a deprecated version of Node.js, please update.

Secondly, your issue is not related to `@terra-money/terra.js`, you have an `EACCES` error.
You should not use `sudo` to install any packages.

You must have something wrong inside your Node installation.
I would recommend to delete anything related to Node and use a version manager like [Volta](https://volta.sh/). It should fix your issue.
