### ISSUE TITLE
error - ./node_modules/@terra-money/webapp-provider/contexts/bank.js:35:0

### ISSUE THREAD

**Issue by moconno** [terra-money/terra.js#81]
Getting this error from webapp-provider: 

error - ./node_modules/@terra-money/webapp-provider/contexts/bank.js:35:0
Module not found: Can't resolve '@terra-dev/use-browser-inactive'

Here is the version I'm using

"dependencies": {
    "@material-ui/core": "^4.11.4",
    "@material-ui/icons": "^4.11.2",
    "@terra-money/wallet-provider": "^0.14.0",
    "@terra-money/webapp-provider": "^0.15.0",
    "@types/react": "^17.0.9",
    "next": "^10.0.0",
    "react": "17.0.1",
    "react-dom": "17.0.1",
    "react-use-clipboard": "^1.0.7",
    "typescript": "^4.3.2"
  }

**Comment by iamssen** [comment]
@moconno 😅 Webapp-provider is an internally used API for Anchor WebApp and is not a topic for this Repo (as SemVer 0.x shows, I do not recommend using it because it can cause a lot of API changes, and I have not yet created a document available to external developers).

If you are interested in this hidden API, you can refer to the source code in the Anchor WebApp Project, and if you write questions in the Anchor WebApp Issue, I will answer them. 

<https://github.com/Anchor-Protocol/anchor-web-app/blob/master/base/src/base/AppProviders.tsx#L85>

<https://github.com/Anchor-Protocol/anchor-web-app/issues>

Thanks!
