### ISSUE TITLE
sign and verify message using `terra.js`

### ISSUE THREAD

**Issue by tkowalczyk** [terra-money/terra.js#95]
Hi, I am wondering if it is possible to sign a message using Terra Extension and in a result receive some signature and then verify if this message was signed with particular address using provided signature.

How it works in Ethereum (pseudocode):

```
var accounts = await web3.eth.getAccounts()
var signature = await web3.eth.personal.sign(message, accounts[0])
```

and later
```
var signing_address = await web3.eth.personal.ecRecover(message, signature)
```

additionally on Ethereum we can also hash a message like below:

```
message = web3.eth.accounts.hashMessage(message)
```

It is `createSignature` function a good starting point? if yes how to verify then, if no how to achieve such flow ?

**Comment by hanjukim** [comment]
There is no such feature exists, but I think you might can do it with secp256k1.ecdsaRecover if it returns signature and recid.   https://github.com/terra-money/terra.js/blob/master/src/key/RawKey.ts#L23-L29

**Comment by Mskalba** [comment]
> There is no such feature exists, but I think you might can do it with secp256k1.ecdsaRecover if it returns signature and recid. https://github.com/terra-money/terra.js/blob/master/src/key/RawKey.ts#L23-L29

But we do not have access to private key which is needed for signing payload. Or am I wrong?

**Comment by zlace0x** [comment]
We are also looking for a solution to verify address ownership without sending a tx.

**Comment by RonniePark** [comment]
Hi. 

I'm a newbie and working on a web application with Terra.
So, wanna sign-in through Terra Station web extension like metamask.

But I couldn't find solution for sign as above and then verify the signature in server side.
Could you please help if there is any guide or document for this kind of process?

Look like, there is growing up many application want use Terra instead of Eth.
This feature might be very useful. :)
   
Thanks.
